export const metadata = {
    title: "Ecommerce Studio",
    description: "Generated by whynotramaa",
  };
  
  export default function RootLayout({
    children,
  }:{
    children: React.ReactNode;
  }) {
    return (
      <html lang="en">
        <body>{children}</body>
      </html>
    );
  }
  